server:
  port: 8080
spring:
  application:
    name: moviebattle-api
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:./database
    username: user
    password: pass
    driverClassName: org.h2.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
springdoc:
  swagger-ui:
    path: /swagger-ui.html
movie-battle:
  omdb:
    url: http://www.omdbapi.com
  tmdb:
    url: https://api.themoviedb.org/3
  jwt:
    secret: jwtadatestsecret
    expiration: 86400000